huggle/huggle3-qt-lx

huggle/editbar.hpp
huggle/editbaritem.hpp
huggle/huggleoption.hpp

GCI - header doxy

---

huggle/Localization/en.xml

Makes it clearer and easier to translate.

Rephrase config-require-delay

---

huggle/Localization/en.xml

A temporary improvement until #146 is fixed comprehensively.

Rephrase wikiedit-tp-fail

---

huggle/Localization/en.xml

Also make it more related to config-require-delay, which is related.

Rephrase config-wait-edit for simplicity

---

huggle/uaareport.cpp

Minor typographical change to comments in code

---

huggle/preferences.cpp
huggle/preferences.ui

Changed a few of the names of the widgets in the Preferences form so they make more sense, instead of just being numbers.

Changed widget names in preferences form to match their function

---

huggle/TranslationStats/main.cpp
huggle/TranslationStats/text.qrc

Adding ro.xml and uk.xml to the language list.

GCI Incorporate a new language into Huggle (Wikimedia)

---

huggle/Localization/en.xml
huggle/apiquery.cpp
huggle/editquery.cpp

Replaced hard-coded strings to translatable ones.

Made strings translatable

---

huggle/Localization/en.xml

Per https://phabricator.wikimedia.org/T148317

fix language

---

huggle/login.cpp

Make error message colored red and display an alert
Bug: T149615

Emphasis the error message of the login form

---

huggle/Localization/zh-hant.xml
huggle/revertquery.hpp

Since normal rollback is always minor, then also software rollback should be.

Mark software rollback as minor edit

---

huggle/mainwindow.cpp
huggle/mainwindow.hpp

Make welcome button also have a menu of options based on the configured options

---

huggle/Localization/en.xml
huggle/configuration.cpp
huggle/configuration.hpp
huggle/huggleparser.cpp
huggle/hugglequeuefilter.cpp
huggle/hugglequeuefilter.hpp
huggle/preferences.cpp
huggle/preferences.ui
huggle/userconfiguration.cpp
huggle/wikiedit.cpp
huggle/wikiedit.hpp
huggle/wikipage.hpp

Allow filtering by watch status

---

huggle/Resources/DefaultConfig.txt
huggle/projectconfiguration.cpp

Allow UAATemplate to be actually configured by projects

---

huggle/mainwindow.cpp
huggle/mainwindow.hpp
huggle/resources.cpp
huggle/resources.hpp
huggle/userconfiguration.cpp
huggle/userconfiguration.hpp

Can we use something better than PageEmptyQueue != "" ?
Bug: https://phabricator.wikimedia.org/T166079

Allow to define the page that must be shown when the queue is empty

---

huggle/Resources/html/empty.html

This change add a small CSS style to the default empty queue page. The cat picture is slightly transparent with rounded edges. So the page looks less aggressive.

Tries to make the empty html page less aggressive

---

huggle/huggleparser.cpp

Clean up freed memory bug

---

README.md
huggle/aboutform.ui
huggle/core.cpp
huggle/login.cpp
huggle/mainwindow.cpp
huggle/terminalparser.cpp
huggle/welcomeinfo.cpp

* Get rid of QT-LX
* Use version from config
Bug: T170565

Change display of versions everywhere

---

huggle/preferences.cpp
huggle/preferences.ui

Add preferences UI to get/set PageEmptyQueue config

---

huggle/vandalnw.cpp

https://phabricator.wikimedia.org/T173675

Disable "send" push button in vandalnw widget if patroller is not connected

---

huggle/Localization/en.xml
huggle/login.cpp
huggle/mainwindow.cpp
huggle/userinfoform.cpp
huggle/vandalnw.cpp
huggle/vandalnw.ui

Don't hesitate to purpose other keys names for strings
python build/localization.py is ok

Few localizations

---

huggle/Localization/en.xml
huggle/configuration.cpp
huggle/configuration.hpp
huggle/mainwindow.cpp
huggle/mainwindow.hpp
huggle/mainwindow.ui
huggle/preferences.ui

f5 now refresh just like any other browser, it fixes some phabricator task as well

implemented refresh

---

huggle/Localization/en.xml
huggle/Resources/html/empty_tab.html
huggle/html.qrc
huggle/mainwindow.cpp
huggle/resources.cpp
huggle/resources.hpp

also some CSS tweaks for empty page

implemented text for new tab

---

huggle/apiquery.cpp
huggle/apiquery.hpp
huggle/reportuser.cpp
huggle/wikiedit.cpp
huggle/wikiedit.hpp

replace rvdiffto with compare

---

huggle/Localization/en.xml
huggle/custommessage.cpp
huggle/exceptionwindow.cpp
huggle/preferences.cpp
huggle/warninglist.cpp

Hey guys. I tried to localize some strings at custommessage.cpp, exceptionwindow.cpp, preferences.cpp and warninglist.cpp.
I hope I didn't make any mistake :)

Localized some English hardcoded strings #GCI2017

---

src/huggle_core/resources.cpp
src/huggle_l10n/Localization/en.xml

I think this tip is as essential as other tips ;)

Added one ProTip

---

src/huggle_ui/editform.cpp

Auto close edit form

---

src/huggle/main.cpp
src/huggle_core/exceptionhandler.cpp
src/huggle_core/iextension.hpp
src/huggle_core/projectconfiguration.cpp
src/huggle_core/querypool.cpp
src/huggle_core/revertquery.cpp
src/huggle_core/userconfiguration.cpp
src/huggle_ui/editform.cpp
src/huggle_ui/hugglequeue.cpp
src/huggle_ui/updateform.cpp
src/huggle_ui/wikipagetagsform.cpp
src/tests/test/tp0003.txt

Might want to wait for huggle/extension-mass-delete#1 so that we can also update the submodule, as this change is somewhat related

fix some typos

---

README.md

Linted README

---

src/huggle_core/huggleparser.cpp

I’ve tweaked frwiki’s config tons of times to try to understand why the automatic detection of user talk page warning levels was not working properly.
In fact it seems that the format of dates present in the signatures in French is different from English, since we put first the date and then the time while enwiki does the opposite. French specificity was not managed at all yet.
This PR adds a bit of logic for French wikis, and adds a few comments around the way.
I think I managed the memory correctly but do not hesitate to check.
Bug: https://phabricator.wikimedia.org/T352815

Add support for French dates

---

MacOS/README.md
documentation/GC.md
documentation/README.md
snap/README
src/huggle/README
windows/README.md
windows64/README.md

I cleaned up the documentation to make things more readable and made things more consistent by adjusting grammar/capitalization.
[ci skip]

Documentation cleanup

---

.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

It doesn't look like there are any other IDE specific files
in this repo right now, but it might be nice to include these.

Add VSCode project files
