huggle/huggle3-qt-lx

huggle/main.cpp

Enable AA_UseHighDpiPixmaps for HiDPI support per [Qt Blog](http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/). 
Apparently the toolbar icons are already high-res enough:

enable AA_UseHighDpiPixmaps for HiDPI support

---

huggle/Localization/en.xml

Sentence should be separated by full stop.

Improve the grammar of history-welcome-msg

---

huggle/Localization/en.xml

Separate sentences should be separated by full stop, not comma.

Improve the grammar of main-revert-newpage

---

huggle/Localization/en.xml

Sentences should be separated by full stop.

Improve the grammar of editquery-invalid-token

---

README.md

`qtscript5-dev` seems to be required to build with Qt5. For the record, I'm using Debian stretch/testing.

README.md: Add qtscript5-dev to the requirements

---

huggle/login.cpp

Since MediaWiki 1.27.0-wmf.13, session tokens can include non-URL safe
characters.
Patch is prepared against the 3.1.18 tag to make getting a new build out easier.

Url encode login token

---

.travis.yml
travis/before_script.sh
travis/script.sh

New forks will default to containers, where sudo must
be explicitly enabled.
Path `/home/travis/build/huggle` does not exist on forks,
so relative paths should be used.
Also use `bash -x` to show the steps being taken.

Fix Travis-CI builds on forks

---

huggle/hugglequeuefilter.cpp

This replacement was presumably to handle spaces following commas, but it also got important spaces in the middle of tags.
Bug: T155333

Fix removal of whitespace in ignored/required tags

---

huggle/Resources/DefaultConfig.txt
huggle/huggleparser.cpp
huggle/hugglequeuefilter.cpp
huggle/hugglequeuefilter.hpp
huggle/preferences.cpp
huggle/preferences.ui
huggle/userconfiguration.cpp
huggle/wikiedit.cpp
huggle/wikiedit.hpp
huggle/wikipage.hpp

This doesn't display anything in the queue filter GUI yet. That'll be a future commit.
Bug: T72723

Allow filtering by category

---

huggle/CMakeLists.txt
huggle/configure

add option `--debug` to configure to make an executable, which is debuggable. If set, huggle_debug will be used will be used as default build dir instead of huggle_release.

option for configure to make debuggable builds

---

huggle/mainwindow.cpp
huggle/projectconfiguration.cpp
huggle/projectconfiguration.hpp
huggle/warninglist.cpp

we used to have this in old huggle but now we also store this option in
user config, so I made 4 options (while in fact only 2 of them really
work now) to let project config maintainers override the user
preference.
This basically adds back the "report" option in config

implemented report mode

---

huggle/Localization/en.xml
huggle/huggletool.cpp
huggle/huggletool.hpp
huggle/mainwindow.cpp
huggle/mainwindow.hpp
huggle/preferences.cpp
huggle/preferences.ui
huggle/querypool.cpp
huggle/userconfiguration.cpp
huggle/userconfiguration.hpp

So that if we are looking on some edit and there was a new edit done to
that very page we are looking at, it automatically reloads to top
revision. This is exactly how it worked in Huggle 2x and we kinda forgot
to implement this. It's optional but enabled by default.

implemented auto-refresh

---

huggle/apiqueryresult.cpp
huggle/core.cpp
huggle/editquery.cpp
huggle/localization.cpp
huggle/preferences.cpp
huggle/processlist.cpp
huggle/query.cpp
huggle/updateform.cpp

We might need to update the headers here, some macros, like _l are conflicting with standard C/C++ headers in OSX Darwin. Moving the includes before our headers that define these macros, should fix the problem.

fix travis

---

huggle/core.cpp
huggle/text.qrc

Added a couple of languages which weren't called to core.cpp and text.qrc, as part of the Google Code-in task "Incorporate new languages into Huggle".
This is my first pull request, and I'm not sure whether I've done this right, so please do let me know if there's anything to be fixed :) thanks

Added languages to Huggle (GCI 2017 task)

---

huggle/Localization/en.xml

#270 Fixed typo in English string (huggle/Localization/en.xml)

Updated en.xml: Fixed typo in English string

---

huggle/configuration.hpp
huggle/login.cpp

Now we check if username was changed after login, if yes we show a
warning and change the username in memory. In case there is more than 1
username change during the process while logging in to multiple wikis,
we abort the login.

fixes T186264

---

src/huggle_core/configuration.cpp
src/huggle_core/configuration.hpp
src/huggle_core/huggleparser.cpp
src/huggle_core/huggleparser.hpp
src/huggle_core/userconfiguration.cpp
src/huggle_core/userconfiguration.hpp
src/huggle_l10n/Localization/en.xml
src/huggle_ui/loginform.cpp
src/huggle_ui/loginform.hpp
src/huggle_ui/mainwindow.cpp

we now store it as huggle.yaml.js instead of huggle3.css
Original idea was to store it as huggle.json or huggle.yaml, which would
probably be more appropriate, but both spaces are unprotected (on
wikimedia sites .json is protected over an extension though).

rewrote user config page to use YAML

---

src/huggle_core/projectconfiguration.cpp
src/huggle_core/projectconfiguration.hpp
src/huggle_core/scripting/jsmarshallinghelper.cpp
src/huggle_core/wikiedit.cpp
src/huggle_core/wikipage.cpp
src/huggle_core/wikipage.hpp
src/huggle_l10n/Localization/en.xml
src/huggle_ui/history.cpp
src/huggle_ui/mainwindow.cpp
src/huggle_ui/wikipagetagsform.cpp
src/huggle_ui/wikipagetagsform.hpp
src/huggle_ui/wikipagetagsform.ui

I also improved the config page -> https://en.wikipedia.org/w/index.php?title=Wikipedia%3AHuggle%2FConfig.yaml&type=revision&diff=855878898&oldid=852506898. However, the descriptions are still not working.

Adding the option "Grouping in {{multiple issues}}" in page tagging

---

snap/snapcraft.yaml
src/build/prepare_snap.sh

Closes #307
Handle path differences that changed in between versions of ``snapcraft``.
Drop explicit submodule handling in favour of ``source-type: git``.

snap: Fix FTBFS

---

src/huggle_l10n/Localization/en.xml

"write" seems more appropriate to me, the link opening an input window.
It is then not necessary to indicate that it is personalized.

Custommessage-title string update

---

src/huggle_core/mediawiki.cpp

This should fix the issue with "talk page edited too recently" for hours after the warning.

Properly handle time zones for timestamps from MW.

---

src/huggle_core/core.cpp

There is a missing `else` keyword in the `Core::ExtensionLoad` function, which can lead to undefined behavior when using the `interface` variable.

Fix a missing 'else' keyword in the Core::ExtensionLoad function

---

.gitignore
src/huggle_ui/reportuser.cpp

When automatic reporting a user to AIV fails for whatever reason (e.g. an edit conflict), Huggle crashes with a segmentation fault.
The cause for this is that the ReportUser object is accessed after it has been freed.
I set up Huggle on my local MediaWiki instance, and protected the AIV page to cause the reporting to fail. After the small patch. Huggle doesn't crash anymore.

Fix silent aiv segfault

---

src/huggle/CMakeLists.txt
src/huggle_core/CMakeLists.txt
src/huggle_l10n/CMakeLists.txt
src/huggle_res/CMakeLists.txt
src/huggle_ui/CMakeLists.txt

Updated CMakeLists.txt for:
* src/huggle
* src/huggle_core
* src/huggle_l10n
* src/huggle_res
* src/huggle_ui
These are now using variables provided by GNUInstallDirs so that we don't have to hardcode paths anymore. This means that libs built for 64-bit systems go into lib64 instead of lib!
I have not tested that this doesn't break anything on Windows or macOS, only on Fedora 33. I'd recommend running at least one test build on each OS before merging this PR.
Also please note comparable [PR](https://github.com/grumpy-irc/libirc/pull/1) for the upstream [libirc](https://github.com/grumpy-irc/libirc).

Use GNUInstallDirs rather than hardcoding paths

---

windows64/veyor.ps1

In the Appveyor script, there is a minor bug, where the documentation for the proper syntax calls for using an equals sign rather than a space. This PR fixes that.

Minor documentation bugfix

---

.github/workflows/huggle.yml

This PR adds a GitHub Actions workflow, written based on the existing Travis-CI and AppVeyor build pipelines.
At this time, no changes have been made to the actual scripts used in the build process, so AppVeyor and Travis-CI will continue to work as they have for the time being.
As currently configured, CI is only run when commits are made to the repository. However, it is a simple process to include PRs, which may be something we want.
I've prepared a simple table showing the differences between the build environments for each operating system.
| Build System | Operating System | Specs |
| ------------- | ------------------ | ------ |
| AppVeyor (Windows) | Windows Server 2012 R2 | [2-core, 6GB RAM](https://www.appveyor.com/docs/build-environment/#build-vm-configurations) |
| Travis-CI …

Create a Github Actions workflow for Linux, macOS and Windows

---

.github/workflows/huggle.yml
travis/before_script.sh

This PR implements a matrix of various OSes and Qt versions for the workflow. Each commit will run every permutation of Qt version and OS version. To see this matrix, you can check [this commit on my fork](https://github.com/phuzion/huggle3-qt-lx/actions/runs/658154510). Adding new Qt versions (for example, if we wanted to add Qt6) is as simple as adding the versions to the `qt-version:` variable.
The Qt versions included are 5.12.10 and 5.15.2.
Windows includes Server 2016 and 2019.
Ubuntu includes 16.04, 18.04 and 20.04.
macOS only includes 10.15 at this time.
Ubuntu and Mac builds now use [jurplel/install-qt-action](https://github.com/jurplel/install-qt-action) to install Qt, which allows us to specify Qt versions without needing to use third-party repos.

[GitHub Actions] Support Multiple OSes and Qt Versions

---

src/huggle_ui/blockuserform.cpp
src/huggle_ui/reportuser.cpp

close() is called on qwidget after completion of task. Could also add a generic message window with "user blocked" or "reported" at the end.

T218740 close report and block forms after completion

---

.travis.yml
CODE_OF_CONDUCT.md
README.md
src/huggle_core/generic.cpp

As some folks may be aware, there have been some recent issues that have come to light regarding the ownership and management of Freenode. As a result of this, the entire volunteer staff of Freenode has resigned.
Many projects are packing up and moving to Libera, which is a new IRC network founded by the previous staff of Freenode.
For more information about this situation, please read this: https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409
This PR points to the new Libera Chat network in a handful of places:
* Documentation such as `CODE_OF_CONDUCT.MD` and `README.md`
* Travis-CI configuration
* The default IRC quit message
I simply performed a `grep -ir freenode .` in the root directory, so if there are any other references to Freenode that I missed, please suggest them …

Switch official IRC network to Libera Chat

---

.github/workflows/huggle.yml

This PR enables GitHub Actions on Pull Requests, in addition to on commits.

Enabling GHA on Pull Requests

---

.github/workflows/huggle.yml

As mentioned in #347, GitHub Actions is removing Ubuntu 16.04 LTS on September 20, 2021. This PR closes #347 by removing 16.04 from the matrix of Ubuntu versions we build against.

Removing Ubuntu 16.04 LTS

---

src/huggle_ui/updateform.cpp

btw: https://huggle.toolforge.org/updater/?version=1&os=example&language=en still returns 3.4.6 as newest version, but 3.4.10 is latest

switch updater url to https and new location

---

.github/workflows/huggle.yml

This PR removes the now deprecated Windows Server 2016 Github Actions runner image, and should fix the currently failing CI. This is a bit of a band-aid fix, as the correct solution is to ensure that Huggle builds on Server 2022 and the latest Visual Studio, which I have tested and does not currently work. This will fix #355.

Remove deprecated Windows Server 2016

---

src/huggle_ui/mainwindow.cpp

Used to fill welcome templates with page title.
Working well on frwiki.
https://fr.wikipedia.org/w/index.php?title=Discussion_utilisateur:La_Casa_Musicale&diff=prev&oldid=210256980 https://fr.wikipedia.org/w/index.php?title=Wikip%C3%A9dia:Huggle/Config.yaml&diff=prev&oldid=210120799

Add $page var in welcomeCurrentUser templating

---

src/huggle_core/message.cpp

Hello, sending a fix for a bug I ran into recently with Qt6 (https://phabricator.wikimedia.org/T383968)
It turns out that unlike QRegExp, when a QRegularExpression starts with \s, it may match whitespace *including newlines*.
So when looking for the start of a section, we might match "\n\n == January 2025 ==" instead of " == January 2025 =="
Then the logic that tries to skip past the header, would instead skip past the first \n, which is still _before_ the header. Then we would think the target header is the start of the next section, and we would end up inserting a message just before the section it was intended to be appended to.
QRegularExpression is available since Qt 5.0 and is recommended. This gets rid of the old QRegExp and fixes the QRegularExpression usage in message.cpp …

fix(Message::appendText): QRegularExpression whitespace bug

---

src/huggle_ui/reportuser.cpp

Another small bug where Huggle would always say a user was not reported at AIV.
The cause is also that QRegularExpression has a different behavior. Here it would only match the single line where the user was reported when the pattern is `.*$username.*`, while QRegExp matched the whole page.
We add the option for DotMatchesEverything, which will match all lines (as before)

fix(ReportUser::checkUserIsReported): Always failed with Qt6

---

src/CMakeLists.txt
src/huggle/CMakeLists.txt
src/huggle_core/CMakeLists.txt
src/huggle_l10n/CMakeLists.txt
src/huggle_res/CMakeLists.txt
src/huggle_ui/CMakeLists.txt

Fixes T391309
Updated 'cmake_minimum_required()' in
all relevant 'CMakeLists.txt' files.
After testing,
I updated all CMakeLists.txt files to use cmake_minimum_required(VERSION 3.5) for clean compatibility with CMake 4.0.0. 
Huggle builds and runs correctly on Linux.
This resolves the compatibility error with CMake 4.0.0:
> Compatibility with CMake < 3.5 has been removed...
Tested and verified that Huggle builds and runs correctly with CMake 4.0.0 on Linux.

Fix: CMake 4.0 compatibility issue (T391309)
